# Generated by Django 4.2.5 on 2023-10-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('adm_no', models.CharField(max_length=255, unique=True)),
                ('grade', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('date_joined', models.DateField(max_length=255)),
            ],
        ),
    ]
